# https://hub.docker.com/r/library/python/tags/
image: python:3.7.9


before_script:
  - python -V
  - pip install -r requirements.txt


test:
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - python tests/run_all_tests.py
